swagger: '2.0'
basePath: /
host: 0.0.0.0
info:
    title: Automate API
    version: 0.0.1
    description:
        This is a simple todo list API
        illustrating go-swagger codegen
        capabilities.
consumes:
    - application/json
definitions:
    Auth0User:
        properties:
            _id:
                type: string
                x-go-name: ID
            client_id:
                type: string
                x-go-name: ClientId
            connection:
                type: string
                x-go-name: Connection
            email:
                type: string
                x-go-name: Email
            family_name:
                type: string
                x-go-name: FamilyName
            given_name:
                type: string
                x-go-name: GivenName
            name:
                type: string
                x-go-name: Name
            password:
                type: string
                x-go-name: Password
            tenant:
                type: string
                x-go-name: Tenant
            user_metadata:
                $ref: '#/definitions/UserMetaData'
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    Auth0UserChangePassword:
        properties:
            client_id:
                type: string
                x-go-name: ClientId
            connection:
                type: string
                x-go-name: Connection
            username:
                type: string
                x-go-name: Email
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    Auth0UserLogin:
        properties:
            audience:
                type: string
                x-go-name: Audience
            client_id:
                type: string
                x-go-name: ClientId
            client_secret:
                type: string
                x-go-name: ClientSecret
            grant_type:
                type: string
                x-go-name: GrantType
            password:
                type: string
                x-go-name: Password
            realm:
                type: string
                x-go-name: Realm
            scope:
                type: string
                x-go-name: Scope
            username:
                type: string
                x-go-name: Email
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    ChangePasswordPayload:
        properties:
            email:
                type: string
                x-go-name: Email
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    EditUserPayload:
        properties:
            date_of_birth:
                type: string
                x-go-name: DateOfBirth
            first_name:
                type: string
                x-go-name: FirstName
            last_name:
                type: string
                x-go-name: LastName
            name:
                type: string
                x-go-name: Name
            phone:
                type: string
                x-go-name: Phone
            photo_file_url:
                type: string
                x-go-name: PhotoFileUrl
            services:
                type: string
                x-go-name: Services
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    GetAuth0UserFieldsPayload:
        properties:
            access_token:
                type: string
                x-go-name: AccessToken
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    LoginPayload:
        properties:
            email:
                type: string
                x-go-name: Email
            password:
                type: string
                x-go-name: Password
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    SignUpPayload:
        properties:
            date_of_birth:
                type: string
                x-go-name: DateOfBirth
            email:
                type: string
                x-go-name: Email
            first_name:
                type: string
                x-go-name: FirstName
            last_name:
                type: string
                x-go-name: LastName
            name:
                type: string
                x-go-name: Name
            password:
                type: string
                x-go-name: Password
            phone:
                type: string
                x-go-name: Phone
            photo_file_url:
                type: string
                x-go-name: PhotoFileUrl
            services:
                type: string
                x-go-name: Services
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
    UserMetaData:
        properties:
            date_of_birth:
                type: string
                x-go-name: DateOfBirth
            phone:
                type: string
                x-go-name: Phone
            photo_file_url:
                type: string
                x-go-name: PhotoFileUrl
            services:
                type: string
                x-go-name: Services
        type: object
        x-go-package: Automate-Go-Backend/databaseModels
paths:
    /GetUser:
        get:
            description: This endpoint returns a user object.
            operationId: GetUser
            produces:
                - application/json
            summary: Get a user.
            tags:
                - user
            responses: 
                '200':
                    description: OK
    /changePassword:
        post:
            description: This endpoint returns a confirmation message.
            operationId: changePassword
            produces:
                - application/json
            summary: changePassword endpoint
            responses: 
                '200':
                    description: OK
    /deleteUser:
        post:
            description: This endpoint returns a confirmation message.
            operationId: deleteUser
            produces:
                - application/json
            summary: delete User endpoint
            responses: 
                '200':
                    description: OK
    /login:
        post:
            description: This endpoint returns a confirmation message.
            operationId: Login
            produces:
                - application/json
            summary: Login in endpoint
            tags:
                - user
            responses: 
                '200':
                    description: OK
    /signUp:
        post:
            description: This endpoint returns a confirmation message.
            operationId: signUp
            produces:
                - application/json
            summary: Sign up endpoint
            tags:
                - user
            responses: 
                '200':
                    description: OK
    /updateUser:
        post:
            description: This endpoint returns a confirmation message.
            operationId: updateUser
            produces:
                - application/json
            summary: update User endpoint
            responses: 
                '200':
                    description: OK
    /Check:
        get:
            description: This endpoint returns a confirmation message.
            operationId: Check
            produces:
                - application/json
            summary: check message
            responses: 
                '200':
                    description: OK
produces:
    - application/json
securityDefinitions:
    oauth2:
        authorizationUrl: /oauth2/auth
        flow: accessCode
        scopes:
            bar: foo
        tokenUrl: /oauth2/token
        type: oauth2
x-meta-array:
    - value1
    - value2
x-meta-array-obj:
    - name: obj
      value: field
x-meta-value: value
