// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ChangePasswordOKCode is the HTTP code returned for type ChangePasswordOK
const ChangePasswordOKCode int = 200

/*
ChangePasswordOK OK

swagger:response changePasswordOK
*/
type ChangePasswordOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewChangePasswordOK creates ChangePasswordOK with default headers values
func NewChangePasswordOK() *ChangePasswordOK {

	return &ChangePasswordOK{}
}

// WithPayload adds the payload to the change password o k response
func (o *ChangePasswordOK) WithPayload(payload string) *ChangePasswordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change password o k response
func (o *ChangePasswordOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangePasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
