// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CheckOKCode is the HTTP code returned for type CheckOK
const CheckOKCode int = 200

/*
CheckOK OK

swagger:response checkOK
*/
type CheckOK struct {
}

// NewCheckOK creates CheckOK with default headers values
func NewCheckOK() *CheckOK {

	return &CheckOK{}
}

// WriteResponse to the client
func (o *CheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
