// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckHandlerFunc turns a function with the right signature into a check handler
type CheckHandlerFunc func(CheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckHandlerFunc) Handle(params CheckParams) middleware.Responder {
	return fn(params)
}

// CheckHandler interface for that can handle valid check params
type CheckHandler interface {
	Handle(CheckParams) middleware.Responder
}

// NewCheck creates a new http.Handler for the check operation
func NewCheck(ctx *middleware.Context, handler CheckHandler) *Check {
	return &Check{Context: ctx, Handler: handler}
}

/*
	Check swagger:route GET /Check check

check message

This endpoint returns a confirmation message.
*/
type Check struct {
	Context *middleware.Context
	Handler CheckHandler
}

func (o *Check) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
