// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Automate API
//
//	This is a simple todo list API illustrating go-swagger codegen capabilities.
//	Schemes:
//	  http
//	Host: 0.0.0.0
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
