// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignUpOKCode is the HTTP code returned for type SignUpOK
const SignUpOKCode int = 200

/*
SignUpOK OK

swagger:response signUpOK
*/
type SignUpOK struct {
}

// NewSignUpOK creates SignUpOK with default headers values
func NewSignUpOK() *SignUpOK {

	return &SignUpOK{}
}

// WriteResponse to the client
func (o *SignUpOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
