// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Auth0UserChangePassword auth0 user change password
//
// swagger:model Auth0UserChangePassword
type Auth0UserChangePassword struct {

	// client Id
	ClientID string `json:"client_id,omitempty"`

	// connection
	Connection string `json:"connection,omitempty"`

	// email
	Email string `json:"username,omitempty"`
}

// Validate validates this auth0 user change password
func (m *Auth0UserChangePassword) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth0 user change password based on context it is used
func (m *Auth0UserChangePassword) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Auth0UserChangePassword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Auth0UserChangePassword) UnmarshalBinary(b []byte) error {
	var res Auth0UserChangePassword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
