// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Auth0UserLogin auth0 user login
//
// swagger:model Auth0UserLogin
type Auth0UserLogin struct {

	// audience
	Audience string `json:"audience,omitempty"`

	// client Id
	ClientID string `json:"client_id,omitempty"`

	// client secret
	ClientSecret string `json:"client_secret,omitempty"`

	// email
	Email string `json:"username,omitempty"`

	// grant type
	GrantType string `json:"grant_type,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// realm
	Realm string `json:"realm,omitempty"`

	// scope
	Scope string `json:"scope,omitempty"`
}

// Validate validates this auth0 user login
func (m *Auth0UserLogin) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth0 user login based on context it is used
func (m *Auth0UserLogin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Auth0UserLogin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Auth0UserLogin) UnmarshalBinary(b []byte) error {
	var res Auth0UserLogin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
