// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangePasswordPayload change password payload
//
// swagger:model ChangePasswordPayload
type ChangePasswordPayload struct {

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this change password payload
func (m *ChangePasswordPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this change password payload based on context it is used
func (m *ChangePasswordPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangePasswordPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangePasswordPayload) UnmarshalBinary(b []byte) error {
	var res ChangePasswordPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
