// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAuth0UserFieldsPayload get auth0 user fields payload
//
// swagger:model GetAuth0UserFieldsPayload
type GetAuth0UserFieldsPayload struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`
}

// Validate validates this get auth0 user fields payload
func (m *GetAuth0UserFieldsPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get auth0 user fields payload based on context it is used
func (m *GetAuth0UserFieldsPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAuth0UserFieldsPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAuth0UserFieldsPayload) UnmarshalBinary(b []byte) error {
	var res GetAuth0UserFieldsPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
