// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SignUpPayload sign up payload
//
// swagger:model SignUpPayload
type SignUpPayload struct {

	// date of birth
	DateOfBirth string `json:"date_of_birth,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// photo file Url
	PhotoFileURL string `json:"photo_file_url,omitempty"`

	// services
	Services string `json:"services,omitempty"`
}

// Validate validates this sign up payload
func (m *SignUpPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sign up payload based on context it is used
func (m *SignUpPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignUpPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignUpPayload) UnmarshalBinary(b []byte) error {
	var res SignUpPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
