// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserMetaData user meta data
//
// swagger:model UserMetaData
type UserMetaData struct {

	// date of birth
	DateOfBirth string `json:"date_of_birth,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// photo file Url
	PhotoFileURL string `json:"photo_file_url,omitempty"`

	// services
	Services string `json:"services,omitempty"`
}

// Validate validates this user meta data
func (m *UserMetaData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user meta data based on context it is used
func (m *UserMetaData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserMetaData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserMetaData) UnmarshalBinary(b []byte) error {
	var res UserMetaData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
